<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Artifika:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arvo:wght@400&display=swap" />
    <link rel="stylesheet" href="/resources/css/HomePage.css" />
  </head>
  <body>
    <div class="main-container">
      <div class="rectangle">
        <div class="flex-row-bb">
          <div class="removal"></div>
          <button class="rectangle-1"></button><span class="order">Order</span
          ><span class="stores">Stores</span>
          <div class="artboard"></div>
          <span class="english">English </span
          ><span class="sign-in">Sign In</span>
        </div>
        <div class="flex-row-c">
          <span class="sourdough-pizza">| Sourdough Pizza</span
          ><span class="pasta">| Pasta</span><span class="toast">| Toast</span
          ><span class="dessert">| Dessert</span
          ><span class="et-cetera">| Et Cetera</span
          ><span class="soup">| Soup</span><span class="drink">| Drink</span>
          <div class="toolbar-icon"></div>
        </div>
        <div class="line"></div>
      </div>
      <span class="sourdough-pizza-2">| Sourdough Pizza</span>
      <div class="flex-row">
        <div class="rectangle-3">
          <div class="aec-cfb-e-bf-aeeec"></div>
          <div class="flex-column">
            <span class="classic-margherita">Classic Margherita</span
            ><span class="fresh-marinara"
              >Made with fresh marinara sauce, mozzarella cheese, and
              basil</span
            ><span class="price">RM 20.00</span
            ><button class="rectangle-4"><span class="add">Add</span></button>
          </div>
        </div>
        <div class="rectangle-5">
          <div class="barbecue-bacon-pizza"></div>
          <div class="flex-column-ba">
            <span class="meat-madness">Meat Madness</span
            ><span class="meat-mania"
              >Our Meat Mania Pizza comes fully loaded with pepperoni, bacon
              crumble, & mild sausage.</span
            ><span class="price-6">RM 28.00</span
            ><button class="rectangle-7"><span class="add-8">Add</span></button>
          </div>
        </div>
      </div>
      <div class="flex-row-be">
        <div class="rectangle-9">
          <div class="chicken-pesto-pizza"></div>
          <div class="flex-column-a">
            <span class="creamy-chicken-pesto">Creamy Chicken Pesto</span
            ><span class="thin-crust"
              >This Creamy Pesto Chicken Pizza has a delicious thin crust and
              juicy sun dried tomatoes.</span
            ><span class="price-b">RM 35.00</span
            ><button class="rectangle-c"><span class="add-d">Add</span></button>
          </div>
        </div>
        <div class="rectangle-e">
          <div class="image"></div>
          <div class="flex-column-fba">
            <span class="bbq-bacon-mushroom">BBQ Bacon Mushroom</span
            ><span class="our-bbq-mushroom-bacon-pizza"
              >Our BBQ Mushroom Bacon Pizza comes fully loaded with BBQ sauce,
              savory mushrooms, and crispy bacon crumble.</span
            ><span class="rm-35">RM 35.00</span
            ><button class="rectangle-f">
              <span class="add-10">Add</span>
            </button>
          </div>
        </div>
      </div>
      <span class="pasta-11">| Pasta</span>
      <div class="flex-row-be-12">
        <div class="rectangle-13">
          <div class="flex-row-14">
            <div class="pesto-pasta"></div>
            <span class="basil-pesto">Basil Pesto</span
            ><span class="contains-nut">*Contains nut</span
            ><span class="creamy-pesto-pasta"
              >This Creamy Pesto Pasta features al dente noodles, rich pesto
              sauce, and juicy cherry tomatoes.</span
            ><span class="rm-20">RM 20.00</span
            ><span class="rm-35-15">RM 35.00</span>
          </div>
          <div class="flex-row-bb-16">
            <div class="rectangle-17"></div>
            <button class="rectangle-18">
              <span class="add-19">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-1a">
          <div class="spaghetti-aglio-olio-seafood"></div>
          <div class="flex-column-ead">
            <span class="aglio-olio">Aglio Olio</span
            ><span class="spaghetti-aglio-olio"
              >This Spaghetti Aglio Olio is a simple delight with garlic-infused
              olive oil, al dente pasta, and a hint of chili.</span
            ><span class="rm-35-1b">RM 35.00</span
            ><button class="rectangle-1c">
              <span class="add-1d">Add</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex-row-1e">
        <div class="rectangle-1f">
          <div class="flex-row-dbae">
            <div class="image-20"></div>
            <span class="mac-cheese">Mac & Cheese</span
            ><span class="mac-n-cheese"
              >This Mac n Cheese is a creamy classic with tender pasta smothered
              in rich, gooey cheese.</span
            ><span class="rm-20-21">RM 20.00</span
            ><span class="rm-35-22">RM 35.00</span>
          </div>
          <div class="flex-row-a">
            <div class="rectangle-23"></div>
            <button class="rectangle-24">
              <span class="add-25">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-26">
          <div class="flex-row-eb">
            <div class="image-27"></div>
            <span class="alfredo">Alfredo</span
            ><span class="pasta-alfredo"
              >This Pasta Alfredo is a creamy indulgence with tender noodles
              coated in a rich, velvety sauce.</span
            ><span class="price-28">RM 20.00</span
            ><span class="price-29">RM 35.00</span>
          </div>
          <div class="flex-row-d">
            <div class="rectangle-2a"></div>
            <button class="rectangle-2b">
              <span class="add-2c">Add</span>
            </button>
          </div>
        </div>
      </div>
      <span class="soup-2d">| Soup</span>
      <div class="flex-row-2e">
        <div class="rectangle-2f">
          <div class="flex-row-30">
            <div class="image-31"></div>
            <span class="pumpkin">Pumpkin</span
            ><span class="pumpkin-soup"
              >This Pumpkin Soup is a cozy blend of creamy pumpkin, warm spices,
              and a hint of sweetness.</span
            ><span class="price-32">RM 20.00</span
            ><span class="price-33">RM 35.00</span>
          </div>
          <div class="flex-row-b">
            <div class="rectangle-34"></div>
            <button class="rectangle-35">
              <span class="add-36">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-37">
          <div class="flex-row-b-38">
            <div class="image-39"></div>
            <span class="pumpkin-3a">Pumpkin</span
            ><span class="pumpkin-soup-3b"
              >This Pumpkin Soup is a cozy blend of creamy pumpkin, warm spices,
              and a hint of sweetness.</span
            ><span class="price-3c">RM 20.00</span
            ><span class="price-3d">RM 35.00</span>
          </div>
          <div class="flex-row-fd">
            <div class="rectangle-3e"></div>
            <button class="rectangle-3f">
              <span class="add-40">Add</span>
            </button>
          </div>
        </div>
      </div>
      <span class="dessert-41">| Dessert</span>
      <div class="rectangle-42">
        <div class="flex-row-43">
          <div class="image-44"></div>
          <span class="creme-brulee">Creme Brulee</span
          ><span class="creme-brulee-45"
            >This Crème Brûlée is a creamy custard topped with a perfectly
            caramelized sugar crust.</span
          ><span class="price-46">RM 20.00</span
          ><span class="price-47">RM 35.00</span>
        </div>
        <div class="flex-row-48">
          <div class="rectangle-49"></div>
          <button class="rectangle-4a"><span class="add-4b">Add</span></button>
        </div>
      </div>
      <span class="et-cetera-4c">| Et Cetera</span>
      <div class="flex-row-f">
        <div class="rectangle-4d">
          <div class="flex-row-b-4e">
            <div class="image-4f"></div>
            <span class="meatball-and-mash">Meatball and Mash</span
            ><span class="meatball-and-mash-description"
              >This Meatball and Mash is a hearty dish with juicy meatballs and
              creamy mashed potatoes.</span
            ><span class="price-50">RM 20.00</span
            ><span class="price-51">RM 35.00</span>
          </div>
          <div class="flex-row-ed">
            <div class="rectangle-52"></div>
            <button class="rectangle-53">
              <span class="add-button">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-54">
          <div class="flex-row-db">
            <div class="image-55"></div>
            <span class="chicken-tenders">Chicken Tenders</span
            ><span class="chicken-tenders-description"
              >These Chicken Tenders are crispy on the outside, tender on the
              inside, and perfectly seasoned.</span
            ><span class="price-56">RM 20.00</span
            ><span class="price-57">RM 35.00</span>
          </div>
          <div class="flex-row-e">
            <div class="rectangle-58"></div>
            <button class="rectangle-59">
              <span class="add-button-5a">Add</span>
            </button>
          </div>
        </div>
      </div>
      <span class="drinks">| Drinks</span>
      <div class="flex-row-fc">
        <div class="rectangle-5b">
          <div class="flex-row-d-5c">
            <div class="image-5d"></div>
            <span class="americano">Americano</span
            ><span class="americano-description"
              >This Americano is a bold, smooth espresso diluted with hot water
              for a rich, full-bodied flavor.</span
            ><span class="price-5e">RM 20.00</span
            ><span class="price-5f">RM 6.00</span>
          </div>
          <div class="flex-row-a-60">
            <div class="rectangle-61"></div>
            <button class="rectangle-62">
              <span class="add-button-63">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-64">
          <div class="flex-row-a-65">
            <div class="image-66"></div>
            <span class="mocha">Mocha</span
            ><span class="mocha-description"
              >This Mocha is a perfect blend of rich espresso, velvety
              chocolate, and creamy milk, topped with a frothy finish.</span
            ><span class="price-67">RM 20.00</span
            ><span class="price-68">RM 10.00</span>
          </div>
          <div class="flex-row-fc-69">
            <div class="rectangle-6a"></div>
            <button class="rectangle-6b">
              <span class="add-button-6c">Add</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex-row-f-6d">
        <div class="rectangle-6e">
          <div class="flex-row-ca">
            <div class="image-6f"></div>
            <span class="cafe-latte">Cafe Latte</span
            ><span class="cafe-latte-description"
              >This Café Latte is a smooth combination of rich espresso and
              steamed milk, topped with a light layer of foam.</span
            ><span class="rm-price">RM 20.00</span
            ><span class="rm-price-70">RM 8.00</span>
          </div>
          <div class="flex-row-ede">
            <div class="rectangle-71"></div>
            <button class="rectangle-72">
              <span class="add-button-73">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-74">
          <div class="flex-row-e-75">
            <div class="image-76"></div>
            <span class="cappuccino">Cappuccino</span
            ><span class="cappuccino-description"
              >This Cappuccino is a frothy mix of rich espresso, steamed milk,
              and a thick layer of velvety foam.</span
            ><span class="rm-price-77">RM 20.00</span
            ><span class="rm-price-78">RM 8.00</span>
          </div>
          <div class="flex-row-a-79">
            <div class="rectangle-7a"></div>
            <button class="rectangle-7b">
              <span class="add-button-7c">Add</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex-row-ed-7d">
        <div class="rectangle-7e">
          <div class="flex-row-7f">
            <div class="image-80"></div>
            <span class="dark-chocolate">Dark Chocolate</span
            ><span class="dark-chocolate-description"
              >This Dark Hot Chocolate is a rich, velvety blend of smooth dark
              chocolate and creamy milk, with a deep, intense flavor.</span
            ><span class="rm-price-81">RM 20.00</span
            ><span class="rm-price-82">RM 9.00</span>
          </div>
          <div class="flex-row-cd">
            <div class="rectangle-83"></div>
            <button class="rectangle-84">
              <span class="add-button-85">Add</span>
            </button>
          </div>
        </div>
        <div class="rectangle-86">
          <div class="flex-row-f-87">
            <div class="image-88"></div>
            <span class="matcha-latte">Matcha Latte</span
            ><span class="matcha-latte-description"
              >This Matcha Latte is a smooth blend of earthy matcha green tea
              and creamy milk, with a delicate, calming flavor.</span
            ><span class="rm-price-89">RM 20.00</span
            ><span class="rm-price-8a">RM 12.00</span>
          </div>
          <div class="flex-row-bc">
            <div class="rectangle-8b"></div>
            <button class="rectangle-8c">
              <span class="add-button-8d">Add</span>
            </button>
          </div>
        </div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
